language: php

php:
  - 7.0

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v

after_failure:
  - echo 'Tu es une buburne'

after_success:
  - echo 'Bien joué'

notifications:
  slack:
    rooms:
    - etdsolutions:5tQeepLBMLrQjXKBhhUk3Xzq#travis_test
    template:
          - "%{repository}@%{branch} (%{commit} by %{author}) : %{message} %{foo} "
          - "Build details: %{build_url}|#%{build_number}"

