language: php

php:
  - 7.0

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v --coverage-text=./coverage.txt ./WordWrapTest.php

addons:
  code_climate:
    repo_token: c8c9fd724d09c0d056b571aeb4e98184245c02873ced2074cbbc2732fc3ec227

after_failure:
  - echo 'Tu es une buburne'

after_success:
  - echo 'Bien joué'
  - php vendor/bin/test-reporter
  - cat ./coverage.txt

notifications:
  slack:
    rooms:
    - etdsolutions:5tQeepLBMLrQjXKBhhUk3Xzq#travis_test
    template:
          - "Repository: %{repository_name}"
          - "Branche: %{branch}"
          - "Commit id: %{commit} par %{author}"
          - "Message de commit: %{commit_message}"
          - "Résultat du build: %{result}"
          - "Build details: %{build_url} #%{build_number}"

