language: php

php:
  - 7.0

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v

after_failure:
  - echo 'Tu es une buburne'

after_success:
  - echo 'Bien joué'

notifications:
  slack:
    rooms:
    - etdsolutions:5tQeepLBMLrQjXKBhhUk3Xzq#travis_test
    template:
          - "Repository: %{repository_name}"
          - "Branche: %{branch}"
          - "Commit id: %{commit} par %{author}"
          - "Message de commit: %{commit_message}"
          - "Résultat du build: %{result}"
          - "Build details: %{build_url} #%{build_number}"

