language: php

php:
  - 7.0

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v ./www_front/calculatorTest.php

after_failure:
  - echo 'Tu es une buburne'

after_success:
  - echo 'Bien joué'

notifications:
  slack:
    'etdsolutions:5tQeepLBMLrQjXKBhhUk3Xzq'
    template:
          - "%{repository} (%{commit}) : %{message} %{foo} "
          - "Build details: %{build_url}"

