language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

after_failure:
  - echo 'T\'es une buburne'

after_success:
  - echo 'Bien joué'
