language: php

php:
  - 7.0
  - 7.1

before_install:
  - composer self-update
  - composer clear-cache

install:
  - composer update

script:
  - ./vendor/bin/phpunit -v ./www_admin/calculatorTest.php

after_failure:
  - echo 'Tu es une buburne'

after_success:
  - echo 'Bien joué'
